<?php
/* Template Name: Ferreta hub */
get_header();$slug=get_post_field('post_name',get_the_ID());$products=wc_get_products(['status'=>'publish','limit'=>8]);
$cards=function(array $items){echo '<div class="hub-cards">';foreach($items as[$title,$copy,$url])echo '<a href="'.esc_url($url).'" class="hub-card"><small>FERRETA / SPACE</small><h3>'.esc_html($title).'</h3><p>'.esc_html($copy).'</p><span>Дізнатися більше →</span></a>';echo '</div>';};
?><main class="hub-page"><header class="hub-hero"><?php the_title('<h1>','</h1>');?></header><?php
switch($slug){
case 'spaces':?><section class="hub-intro"><h2>Світло, яке відповідає<br>вашому <em>простору</em>.</h2><p>Починайте зі сценарію, а не з моделі. Менеджер допоможе зібрати композицію з доступних SKU.</p></section><?php $cards([['Доріжка','Ритм світла для маршруту від хвіртки до тераси.','/project-request/'],['Сад','М’які акценти для вечірніх прогулянок.','/project-request/'],['Тераса','Світлова атмосфера для розмов після заходу сонця.','/project-request/'],['Вхідна група','Чіткий перший акцент біля дому чи закладу.','/project-request/'],['HoReCa','Для ресторанів, готелів і глемпінгів.','/b2b/'],['Громадський простір','Проєктний підбір для масштабних об’єктів.','/b2b/']]);break;
case 'sets':?><section class="hub-intro"><h2>Композиції, у яких<br>світильники працюють <em>разом</em>.</h2><p>Склад і доступність комплекту підтверджує менеджер — без обіцянок, не підкріплених залишками.</p></section><?php $cards([['Вхідна група','Два високі світильники для симетричного акценту.','/project-request/'],['Доріжка до тераси','4–6 моделей 50 / 75 см.','/project-request/'],['Садова алея','Серія з 6–10 світильників.','/project-request/'],['Тераса для вечора','Композиція під конфігурацію простору.','/project-request/']]);break;
case 'projects':?><section class="hub-intro"><h2>Вдохновение, яке<br>починається з <em>простору</em>.</h2><p>Публікуємо лише погоджені об’єкти. Завантажте фото ділянки, щоб отримати подібне рішення.</p></section><section class="project-placeholder"><span>FERRETA PROJECTS</span><h2>Ваш простір може стати наступним проєктом.</h2><a class="button" href="/project-request/">Хочу подібне рішення</a></section><?php break;
case 'about':?><section class="hub-intro"><h2>Ferreta — це світлові<br>об’єкти для <em>відкритого</em> простору.</h2><p>Ми не публікуємо непідтверджені заяви про матеріали, технології чи походження. Цю сторінку адміністратор наповнює погодженими кадрами процесу та фактами виробництва.</p></section><?php break;
case 'materials':?><section class="hub-intro"><h2>Матеріали, догляд<br>і <em>відповідальність</em>.</h2><p>Технічні параметри кожної моделі з’являються в картці товару лише після підтвердження виробництвом.</p></section><section class="faq-list"><details open><summary>Що публікується в характеристиках?</summary><p>Лише підтверджені виробником габарити, вага, покриття, комплектація, гарантія та інші параметри.</p></details><details><summary>Як отримати специфікацію?</summary><p>Надішліть запит для проєкту — менеджер надасть актуальний документ за наявності.</p></details></section><?php break;
case 'journal':?><section class="hub-intro"><h2>Ідеї для тих,<br>хто бачить <em>простір</em>.</h2><p>Журнал наповнюється через WordPress без редагування коду.</p></section><?php $cards([['Світло вздовж доріжки','Як вибудувати ритм і не перевантажити сад.','/spaces/'],['Висота як інструмент','Як читати різні висоти у вечірній композиції.','/shop/'],['Тераса після заходу сонця','Сценарій для тихого вечора на відкритому повітрі.','/spaces/']]);break;
case 'b2b':?><section class="hub-intro"><h2>Для тих, хто<br>проєктує <em>враження</em>.</h2><p>Для ландшафтних дизайнерів, архітекторів, HoReCa, девелоперів і дилерів: запит каталогу, проєктного підбору та доступних умов співпраці.</p></section><?php $cards([['Проєктний підбір','Підберемо моделі під ваш сценарій.','/project-request/'],['Специфікація','Надаємо підтверджені дані за запитом.','/project-request/'],['Партнерська співпраця','Запит для дилера чи дизайнера.','/project-request/']]);break;
case 'project-request':?><section class="lead-page"><p class="kicker">FERRETA PROFESSIONAL</p><h2>Розкажіть про свій <em>простір</em>.</h2><p>Заявка створить B2B-лід та надішле повідомлення відповідальному менеджеру.</p><form id="project-lead"><input type="hidden" name="type" value="project"><label>Ім’я<input name="name" required></label><label>Телефон<input name="phone" required></label><label>Email<input name="email" type="email"></label><label>Тип об’єкта<select name="object_type"><option>Приватний простір</option><option>Дизайнерський проєкт</option><option>HoReCa</option><option>Дилерство</option></select></label><label>Опишіть простір<textarea name="comment" rows="5" placeholder="Місто, довжина доріжки, бюджет, побажання"></textarea></label><label class="consent"><input type="checkbox" name="consent" required> Погоджуюся на обробку персональних даних</label><button class="button">Надіслати запит</button><output></output></form></section><?php break;
case 'delivery':?><section class="hub-intro"><h2>Прозорий шлях<br>від кошика до <em>простору</em>.</h2><p>Доступні методи доставки та оплати адміністратор вмикає після підключення офіційних модулів Нової Пошти й обраного платіжного провайдера.</p></section><?php break;
case 'warranty':?><section class="hub-intro"><h2>Гарантія потребує<br>точних <em>умов</em>.</h2><p>Фінальний гарантійний текст і терміни публікуються після надання виробником.</p></section><?php break;
case 'faq':?><section class="faq-list"><details open><summary>Чи потрібне підключення до електромережі?</summary><p>Ні, Ferreta позиціонується як автономне освітлення на сонячній панелі.</p></details><details><summary>Де краще встановлювати світильник?</summary><p>У відкритому місці з достатнім денним освітленням.</p></details><details><summary>Скільки працює світильник?</summary><p>Точні показники залежать від конкретної моделі й публікуються після підтвердження виробником.</p></details></section><?php break;
case 'contacts':?><section class="lead-page"><h2>Почнімо з<br><em>розмови</em>.</h2><p>Залиште запит — менеджер зв’яжеться з вами.</p><a class="button" href="/project-request/">Надіслати запит</a></section><?php break;
default:?><section class="hub-intro"><h2><?php the_title();?></h2><p>Фінальний юридичний або сервісний текст додає власник бізнесу до публікації.</p></section><?php };?></main><?php get_footer();?>
